name = "macro-observer"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "macro-db"
database_id = "c50f3196-4ed6-46d1-a87f-81450c58d36a"

[[kv_namespaces]]
binding = "SESSIONS"
id = "0604466813d34727ac7e1827e92eb93d"
preview_id = "dc99ad097771478fb7a508abf12f3769"   # run: wrangler kv namespace create SESSIONS --preview


